### ISSUE TITLE
Update Cylc to handle new FSD

### ISSUE THREAD

**Issue by tdivoll** [WilhelmusLab/ice-floe-tracker-pipeline#149]
Initial To-Dos:
- [x] make a new Cylc template for FSD routine: https://github.com/WilhelmusLab/ebseg/pull/43
- [x] auto populate the Jinja template with the flag needed to trigger FSD in the CLI preprocessing wrapper

This needs a lot of changes to the IceFloeTracker.jl, ebseg and ice-floe-tracker-pipeline repos. More detailed To-Dos:

## IceFloeTracker.jl 

Prototype branch: https://github.com/WilhelmusLab/IceFloeTracker.jl/tree/jghrefactor/support-labeled-segmented-images

- [x] Add support for `labeled` segmented floe images in https://github.com/WilhelmusLab/IceFloeTracker.jl/pull/458
  - [x] `_pairfloes`
  - [x] `addfloemasks!`
  - [x] `bwtraceboundary`
  - [x] `cropfloe`
- [x] Add support for floating point centroids in `convertcentroid!` (either by 
  - updating lookup code to round the numbers as in the prototype, or https://github.com/WilhelmusLab/IceFloeTracker.jl/pull/458
  - doing a proper affine transformation.)
- [x] Fix a broken call to `sort!` in `find_reflectance_peaks` (this seems to be fixed. Might not need to do it.)
- [x] Fix conda environment creation (see #177 for how to do this in the pipeline repo)

## ebseg

Prototype branch: https://github.com/WilhelmusLab/ebseg/tree/update-regionprops-names

- [ ] chore: remove extra pytest configuration for vscode
- [x] feature: add better parsing of bounding boxes (allow different formats) https://github.com/WilhelmusLab/ebseg/pull/60
- [x] feature: add support for falsecolor band 721 https://github.com/WilhelmusLab/ebseg/pull/59 
- [x] refactor: `get_region_properties` rename props in output file to match IceFloeTracker.jl https://github.com/WilhelmusLab/ebseg/pull/61
- [x] feature: `get_region_properties` add bounding box and convex area https://github.com/WilhelmusLab/ebseg/pull/61

## ice-floe-tracker-pipeline

Prototype branch: https://github.com/WilhelmusLab/ice-floe-tracker-pipeline/tree/jghrefactor/6-makeh5files-support

### Satellite Overpass Identification Tool
- [x] Add a docker container for SOIT #175 
- [x] Update SOIT to use pipx and inline dependency #175
- [ ] #213

### IFTPipeline.jl

- [x] refactor: merge Julia files into a single directory `IFTPipeline.jl` with `src/` and `test/` and the `Project.toml` and `Manifest.toml` files. #170 
- [x] Set up CLI wrapper to write to STDOUT and STDERR by default (use `2>&1 file` syntax to redirect to file if needed) #179 
- [x] Set up CLI wrapper to handle a `--debug` flag to write more output to terminal
- Add a version of the following tasks to work on single generic files (TIFF, CSV), including CLI and tests:
  - [x] landmask generation
  - [x] preprocessing
  - [x] extract features
  - [x] export to H5 files
- Add a version of the following tasks to work on explicit collections of generic files (TIFF, CSV) including CLI and tests:
  - [x] track floes
- [x] refactor: make new version of the cylc workflow which uses the single file inputs and outputs
- [x] make a docker container which has an entry point for the IFT CLI application. #174 
- [x] extend choose_dtype function with new types #169 

### Cylc

- [x] feature: add docker support to new cylc workflow file, but don't lose the ability to run locally
- [x] chore: clean up cylc files – there should be one canonical cylc file which has all the options

**Comment by hollandjg** [comment]
Added support for cylc and FSD with https://github.com/WilhelmusLab/ebseg/pull/43

**Comment by hollandjg** [comment]
This needs a lot of changes to the IceFloeTracker.jl, ebseg and ice-floe-tracker-pipeline repos:

## IceFloeTracker.jl 

Prototype branch: https://github.com/WilhelmusLab/IceFloeTracker.jl/tree/jghrefactor/support-labeled-segmented-images
- [ ] Add support for `labeled` segmented floe images in 
  - [ ] `_pairfloes`
  - [ ] `addfloemasks!`
  - [ ] `bwtraceboundary`
  - [ ] `cropfloe`
- [ ] Add support for floating point centroids in `convertcentroid!` (either by 
  - updating lookup code to round the numbers as in the prototype, or 
  - doing a proper affine transformation.)
- [ ] Fix a broken call to `sort!` in `find_reflectance_peaks`
- [ ] Fix conda environment creation

## ebseg

Prototype branch: https://github.com/WilhelmusLab/ebseg/tree/update-regionprops-names

- [ ] chore: remove extra pytest configuration for vscode
- [ ] feature: add better parsing of bounding boxes (allow different formats)
- [ ] feature: add support for falsecolor band 721 https://github.com/WilhelmusLab/ebseg/pull/59 
- [ ] refactor: `get_region_properties` rename props in output file to match IceFloeTracker.jl
- [ ] feature: `get_region_properties` add bounding box and convex area

## ice-floe-tracker-pipeline

Prototype branch: https://github.com/WilhelmusLab/ice-floe-tracker-pipeline/tree/jghrefactor/6-makeh5files-support

- [ ] refactor: merge Julia files into a single directory `IFTPipeline.jl` with `src/` and `test/` and the `Project.toml` and `Manifest.toml` files.
- [ ] Set up CLI wrapper to write to STDOUT and STDERR as default (use `2>&1 file` syntax to redirect to file if needed)
- [ ] Set up CLI wrapper to handle a `--debug` flag to write more output to terminal
- Add a version of the following tasks to work on single generic files (TIFF, CSV), including CLI and tests:
  - [ ] landmask generation
  - [ ] preprocessing
  - [ ] extract features
  - [ ] export to H5 files
- Add a version of the following tasks to work on explicit collections of generic files (TIFF, CSV) including CLI and tests:
  - [ ] track floes
- [ ] refactor: make new version of the cylc workflow which uses the single file inputs and outputs
- [ ] feature: add docker support to new cylc workflow file, but don't lose the ability to run locally
- [ ] chore: clean up cylc files – there should be one canonical cylc file which has all the options
  - [ ] Is there a way we could analyze the data every time Aqua and Terra pass over the area? Rather than every day, do every overpass?
- [ ] make a docker container which has an entry point for the IFT CLI application.
